<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-ManufacturingSystem-f826acc6-c0e6-4a80-8169-b6889b47d3a5</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../Libraries/InternalQueue/InternalQueue.csproj" />
        <ProjectReference Include="..\..\Libraries\Broadcaster\Broadcaster.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="ManufacturingSystem.Test" />
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    </ItemGroup>
</Project>
